config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments 
  end
  
  devise_for :users
  
  resources :users, only: [:index, :show]do
    resources :notifications
  end

  get 'people' => 'users#people', as: :people

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true
  validates :lastname, presence: true

  has_attached_file :photo, styles: {medium: "300x200", small: "140x140", thumb: "100x100"}, :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/    
	has_many :posts
	has_and_belongs_to_many :user
	has_many :comments
	has_many :notifications
  has_many :friends

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 	before_action :authenticate_user!, :set_friends

	def index

	end

	def people
		@users = User.all.order(:name)
	end

	# GET users/:id
	def show
		# Usuario al cual el usuario actual esta accediendo
    	@user = User.find(params[:id])

    	# Solicitudes enviadas por el usuario actual al usuario que se esta accediendo
		@notifications_send = Notification.all.where(user_send_id: current_user.id , user_receive_id: @user.id)
  	end

  	private

  	def set_friends
  		@friends = current_user.friends
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<ul class="media-list">
	<% @friends.each do |friend| %>
        
  <li class="media">
  	<% @current = User.find(friend.friend_id) %>
    <%= image_tag(@current.photo.url(:small), class: 'pull-left') %>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to @current.name, user_path(@current) %></h4>
      <p> <%=  @current.lastname %></p>
    </div>

  </li>
</ul>

 <% end %>

app/views/users/people.html.erb
<ul class="media-list">
	<% @users.each do |user| %>
        
  <li class="media">
    <%= image_tag(user.photo.url(:small), class: 'pull-left') %>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to user.name, user_path(user) %></h4>
      <p> <%=  user.lastname %></p>
    </div>

  </li>
</ul>

 <% end %>

app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-6 col-md-5">
        <%= image_tag(@user.photo.url(:small), class: 'photo') %>
        <h1><%= @user.name %> <%= @user.lastname %></h1>
        
        <!-- Quitar los botones cuando el perfil es el del usuario -->
        <% if not current_user.id == @user.id%>
        <!-- Si el usuario no me ha enviado una solicitud, => lo puedo annadir como amigo -->
            <% if not @notifications_send.count == 0 %>
                <!-- Solicitudes recibidas por el usuario al que se esta accediendo -->
                <%@rec = Notification.all.where(user_send_id: @user.id, user_receive_id: current_user.id)%> 
               <% if not @rec.count == 0 %>
                    <%= link_to "Friend", "", class: "btn btn-success" %>
               <% elsif %>
                    <%= link_to "Solicitud Enviada", "", class: "btn btn-success" %>
               <% end -%>
           
            <% else %>
    		  <%= link_to "Add Friend", new_user_notification_path([@user], :user => @user.id), class: "btn btn-success" %>
            <% end -%>
    	<% else %>
    		<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default" %>
    	<% end -%>
   		<%= link_to "Back", users_path, class: "btn btn-default" %>

    </div>

<div>
<div class="panel-style">
    <div class="panel panel-info">  
        <div class="panel-heading">Personal Information</div>
            <div class="panel-body">      
        <ul>
            <% if @user.is_female %>
                <li><h5>Female</h3></h5>
            <% else %>
                <li>Male</li>
            <% end %>
            <li><h5>Birthdate: <%= @user.birthdate %></h5></li>
            <li><h5><%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.birthdate) + " old")) unless @user.birthdate.blank? %></h5></li>
            <li><h5><%= @user.country unless @user.country.blank? %></h5></li>

        </ul>
            </div>   
    </div>
</div>
</div>
</div>